/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete1;

/**
 *
 * @author ADRIAN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    private Hotel hotel;
    private Administrador A1;
    private Recepcionista R1;
    
    private Habitacion H1;
    private Habitacion H2;
    private Habitacion H3;
    private Habitacion H4;
    private Habitacion H5;
    private Habitacion H6;
    private Habitacion H7;
    
    private Huesped Hu1;
    private Huesped Hu2;
    private Huesped Hu3;
    private Huesped Hu4;
    
    private ServicioAdicional SA1;
    private ServicioAdicional SA2;
    private ServicioAdicional SA3;
    
 
    public Login() 
    {
        initComponents();
        hotel = new Hotel();
        //CREAR ALGUNOS EMPLEADOS
        this.A1 = new Administrador("A1", 1111, 674389, "Sergio", "Perez", "Administrador");
        this.R1 = new Recepcionista("R1", 4444, 678686, "Maribel", "Yi", "Recepcionista");
        
        this.H1 = new Habitacion(1,1,100,"Simple",true,true);
        this.H2 = new Habitacion(2,1,100,"Simple",true,true);
        this.H3 = new Habitacion(3,2,200,"Doble",true,true);
        this.H4 = new Habitacion(4,2,200,"Doble",true,true);
        this.H5 = new Habitacion(5,2,300,"Suite",true,true);
        this.H6 = new Habitacion(6,2,300,"Suite",true,true);
        this.H7 = new Habitacion(7,1,300,"Suite",true,true);
        
        this.Hu1 = new Huesped(6769871, "Juan", "Perez", "datos");
        this.Hu2 = new Huesped(1234567, "Luciana", "Yi", "datos");
        this.Hu3 = new Huesped(9753975, "Sebastian", "Torre", "datos");
        this.Hu4 = new Huesped(3651826, "Mateo", "Quispe", "datos");
        
        this.SA1 = new ServicioAdicional("Lavanderia", 40);
        this.SA2 = new ServicioAdicional("Frigobar", 15);
        this.SA3 = new ServicioAdicional("Roomservice", 25);
        
        
        //AGREGAR A ARREGLO EMPLEADOS
        hotel.getEmpleados().add(A1);
        hotel.getEmpleados().add(R1);
        
        hotel.getHabitaciones().add(H1);
        hotel.getHabitaciones().add(H2);
        hotel.getHabitaciones().add(H3);
        hotel.getHabitaciones().add(H4);
        hotel.getHabitaciones().add(H5);
        hotel.getHabitaciones().add(H6);
        hotel.getHabitaciones().add(H7);
        
        hotel.getHuespedes().add(Hu1);
        hotel.getHuespedes().add(Hu2);
        hotel.getHuespedes().add(Hu3);
        hotel.getHuespedes().add(Hu4);
        
        hotel.getServicios().add(SA1);
        hotel.getServicios().add(SA2);
        hotel.getServicios().add(SA3);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("USUARIO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CONTRASEÑA");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("LOGIN");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jButton1)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usuario = this.jTextField1.getText();
        int contraseña = Integer.parseInt(this.jTextField2.getText());
        if(hotel.login(usuario, contraseña)!= null)
        {
            if(hotel.login(usuario, contraseña)instanceof Administrador)
            {
                AdministradorG pantalla2 = new AdministradorG(hotel, A1);
                pantalla2.setVisible(true);
                //this.dispose();
            }
            else
            {
                RecepcionistaG pantalla2 = new RecepcionistaG(hotel, R1);
                pantalla2.setVisible(true);
                //dispose();
            }
        }
        else
        {
            String texto = "El usuario o la contraseña son incorrectos";
            ErrorG p2 =  new ErrorG(texto);
            p2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
